const GET_ALL_BREEDS = "GET_ALL_BREEDS";
const GET_BREED_BY_NAME = "GET_ALL_BREEDS";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const FILTER_BY_TEMP = "FILTER_BY_TEMP";
const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SORT_BY = "SORT_BY";

export {
  GET_ALL_BREEDS,
  GET_BREED_BY_NAME,
  GET_TEMPERAMENTS,
  FILTER_BY_TEMP,
  FILTER_BY_ORIGIN,
  SET_CURRENT_PAGE,
  SORT_BY,
};
